package com.example.ai_review.common;

public enum ErrorCode {
    BAD_REQUEST,
    INVALID_PR_URL,
    INVALID_DIFF_TEXT,
    GITHUB_PR_NOT_FOUND,
    GITHUB_RATE_LIMITED,
    GITHUB_AUTH_FAILED,
    GITHUB_TOKEN_REQUIRED,
    GITHUB_NETWORK_ERROR,
    GITHUB_UPSTREAM_ERROR,
    DEEPSEEK_API_KEY_MISSING,
    DEEPSEEK_AUTH_FAILED,
    DEEPSEEK_NETWORK_ERROR,
    DEEPSEEK_RESPONSE_INVALID,
    DEEPSEEK_UPSTREAM_ERROR,
    INTERNAL_ERROR
}
